name: Code Quality

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14.17.3"]
    steps:
      - name: checkout Code
        uses: actions/checkout@v2.3.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare environment
        run: npm install -g npm@latest
      - name: npm install deps
        uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
        env:
          CI: true