name: Image analysis and sec scan

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  image_scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v2.3.2
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=test-$(echo "${{ github.sha }}")" >> $GITHUB_ENV
      - name: Build the Docker image
        run: |
          docker build -t docker.io/comfucios/dr_serverless:${{ steps.extract_tag.outputs.tag }} .
      - name: Run vulnerability scanner on image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/comfucios/dr_serverless:${{ steps.extract_tag.outputs.tag }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
      - name: Tidy up
        if: always()
        run: |
          docker image rm docker.io/comfucios/dr_serverless:${{ steps.extract_tag.outputs.tag }}