name: Image analysis and sec scan

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  image_scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v2.3.2
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=test-$(echo "${{ github.sha }}")" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: comfucios/dr_serverless:${{ env.IMAGE_TAG }}
      - name: Run vulnerability scanner on image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "comfucios/dr_serverless:${{ env.IMAGE_TAG }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"