name: Code analysis and sec scans

on:
  pull_request:
  workflow_dispatch:

jobs:
  npm-audit:
    strategy:
      matrix:
        node-version: ["16.13.0"]
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install deps
        uses: bahmutov/npm-install@v1
      - uses: oke-py/npm-audit-action@v1.7.3
        with:
          audit_level: moderate
          github_token: ${{ secrets.TOKEN }}
          issue_assignees: ${{secrets.USER}}
          issue_labels: vulnerability
          dedupe_issues: true
  code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v2.3.2
      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
  njsscan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v2.3.2
      - name: njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@v6
        with:
          args: "--config=./.njsscan ."